# Generated by Django 5.1.3 on 2024-11-30 23:15

import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='name',
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='name',
        ),
        migrations.AddField(
            model_name='applicant',
            name='SoP',
            field=models.FileField(null=True, upload_to='applicant_documents/'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='academic_level',
            field=models.CharField(choices=[('GRAD', 'Graduate'), ('UNDER', 'Undergradute'), ('HS', 'High School')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='address1',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='address2',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='department',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='enrollment_status',
            field=models.CharField(choices=[('FT', 'Full Time'), ('PT', 'Part Time')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='first_name',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='gpa',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='last_name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, unique=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='scholarship',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.scholarship'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='additional_info',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='department',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='donor',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='open_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scholarship',
            name='organization',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='renewal_type',
            field=models.CharField(choices=[('AR', 'Automatic Renewal'), ('APR', 'Application-Based Renewal'), ('MBS', 'Merit-Based Renewal'), ('NBR', 'Need-Based Renewal'), ('CR', 'Conditional Renewal'), ('PR', 'Partial Renewal'), ('NULL', 'None')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='scholarship_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='amount',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failed_login_attempts', models.IntegerField(default=0)),
                ('is_locked', models.BooleanField(default=False)),
                ('password_requires_change', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
