# Generated by Django 5.1.3 on 2024-12-02 03:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_applicant_scholarship_applicant_scholarships_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='scholarships',
        ),
        migrations.AddField(
            model_name='applicant',
            name='scholarship',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.scholarship'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
