# Generated by Django 5.1.3 on 2024-12-07 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_applicant_user_alter_application_applicant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='normalized_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
