# Generated by Django 5.1.3 on 2024-12-07 20:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_scholarship_normalized_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
