# Generated by Django 5.1.3 on 2024-12-07 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_scholarship_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarship',
            name='normalized_amount',
        ),
    ]
