# Generated by Django 5.1.3 on 2024-12-07 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_scholarship_normalized_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
